// Downloads Philippine mountain photos from Wikimedia Commons, converts them to WebP,
// and writes src/data/credits.ts with the attribution each license requires.
// Usage: node scripts/fetch-images.mjs
import sharp from 'sharp';
import { writeFile } from 'node:fs/promises';

const UA = { 'User-Agent': 'MMS-Official-Site/1.0 (image build script)' };

const images = [
  { slug: 'hero-pulag-sunrise', width: 2400, file: 'File:Mount Pulag Summit.jpg', place: 'Mt. Pulag, Benguet' },
  { slug: 'pulag-sea-of-clouds', width: 1400, file: 'File:Mount Pulag, Kabayan, Philippines (Unsplash).jpg', place: 'Mt. Pulag, Benguet' },
  { slug: 'apo', width: 1400, file: 'File:The Ring of Mt. Apo.jpg', place: 'Mt. Apo, Mindanao' },
  { slug: 'batulao', width: 1400, file: 'File:Dinosaur Back Mountain of Batulao.jpg', place: 'Mt. Batulao, Batangas' },
  { slug: 'page-bmc', width: 2400, file: 'File:Verdant Mt. Pulag grasslands.jpg', place: 'Mt. Pulag, Benguet' },
  { slug: 'page-open-climbs', width: 2400, file: 'File:Mount Pulag Hikers.jpg', place: 'Mt. Pulag, Benguet' },
  { slug: 'page-outreach', width: 2400, file: 'File:Kibuñgan Cross country (KXC) -5.jpg', place: 'Kibungan, Benguet' },
  { slug: 'page-sart', width: 2400, file: 'File:Majestic Pulag.jpg', place: 'Mt. Pulag, Benguet' },
  { slug: 'page-announcements', width: 2400, file: 'File:Mt. Ulap 3.jpg', place: 'Mt. Ulap, Benguet' },
  { slug: 'page-surveys', width: 2400, file: 'File:Mt.Batulao.jpg', place: 'Mt. Batulao, Batangas' },
  { slug: 'gallery-pulag-sunrise', width: 1400, file: 'File:Hikers watching sunrise at Mount Pulag summit.jpg', place: 'Mt. Pulag, Benguet' },
  { slug: 'gallery-lake-venado', width: 1000, file: 'File:Lake Venado.jpg', place: 'Lake Venado, Mt. Apo' },
  { slug: 'gallery-batulao-ridge', width: 1000, file: 'File:Batulao - Allan Jay Quesada.jpg', place: 'Mt. Batulao, Batangas' },
  { slug: 'gallery-kibungan', width: 1000, file: 'File:Kibuñgan Cross country (KXC) -1.jpg', place: 'Kibungan, Benguet' },
  { slug: 'gallery-marami', width: 1000, file: 'File:Mt. Marami.jpg', place: 'Mt. Marami, Cavite' },
  { slug: 'gallery-tarak', width: 1000, file: 'File:Tarak Ridge campsite, Mount Mariveles.jpg', place: 'Tarak Ridge, Bataan' },
];

const strip = (html = '') => html.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

const api = 'https://commons.wikimedia.org/w/api.php?' + new URLSearchParams({
  action: 'query', format: 'json', titles: images.map((i) => i.file).join('|'),
  prop: 'imageinfo', iiprop: 'url|extmetadata', iiurlwidth: '2400',
});
const data = await (await fetch(api, { headers: UA })).json();
const info = {};
for (const p of Object.values(data.query.pages)) info[p.title] = p.imageinfo[0];
for (const n of data.query.normalized ?? []) info[n.from] = info[n.to];

const credits = [];
for (const img of images) {
  const ii = info[img.file];
  if (!ii) throw new Error(`Not found: ${img.file}`);
  const buf = Buffer.from(await (await fetch(ii.thumburl ?? ii.url, { headers: UA })).arrayBuffer());
  await sharp(buf).rotate().resize({ width: img.width, withoutEnlargement: true }).webp({ quality: 80 }).toFile(`public/images/${img.slug}.webp`);
  const m = ii.extmetadata;
  credits.push({
    src: `/images/${img.slug}.webp`,
    place: img.place,
    title: img.file.replace(/^File:/, '').replace(/\.[a-z]+$/i, ''),
    author: strip(m.Artist?.value) || 'Unknown',
    license: m.LicenseShortName?.value ?? 'See source',
    licenseUrl: m.LicenseUrl?.value ?? '',
    source: ii.descriptionurl,
  });
  console.log(`✓ ${img.slug} — ${credits.at(-1).author} (${credits.at(-1).license})`);
}

await writeFile('src/data/credits.ts', `// Generated by scripts/fetch-images.mjs — do not edit by hand.
export interface PhotoCredit {
  src: string;
  place: string;
  title: string;
  author: string;
  license: string;
  licenseUrl: string;
  source: string;
}

export const photoCredits: PhotoCredit[] = ${JSON.stringify(credits, null, 2)};
`);
